#!/bin/bash

# Use this script to create a new Course Repo.
# Run it from the root of this repo, using 
# the 'dot' command to source the script like this:
#
# . ./generate-course-repo REPONAME
# 
# eg:
# . ./generate-course-repo amman-102d3

# Add files
mkdir ../$1
cd curriculum
rsync -Rq */README.md README.md ../../$1 2>&1 >/dev/null
cp -R class-06/starter-code/ ../../$1/class-06/starter-code/

echo "********"
echo "  Files copied..."
echo "  Jumping to new folder..."

# Sync repo
cd ../../$1
git init
git add .
git commit -m "added initial course READMEs."
echo 
echo 
echo "********"
echo "  Repo created!"
echo 
echo "--> Now, add origin and push: git remote add origin REPO-URL"
