import Head from 'next/head';
import Link from 'next/link';


export default function Home() {
    return (
        <>
            <Head>
                <title>Expert Eight Ball</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className='flex items-center justify-between p-4 bg-gray-500 text-gray-50'>
                <h1>Expert 8 Ball</h1>
                <p>1 questions answered</p>
            </header>
            <main className=''>


            </main>
            <footer className='p-4 mt-8 bg-gray-500 text-gray-50'>
                <Link href="/careers">
                    Careers
                </Link>
            </footer>
        </>
    );
}
