[tool.poetry]
name = "codefellows"
version = "0.6.0"
description = "Commonly needed Python modules"
authors = ["codefellows <jb@codefellows.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
