# Generated by Django 2.2.1 on 2019-08-13 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0002_thing_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thing',
            unique_together={('user', 'name')},
        ),
    ]
